README.md
charts/mapproxy/.helmignore
charts/mapproxy/Chart.yaml
charts/mapproxy/README.md
charts/mapproxy/templates/NOTES.txt
charts/mapproxy/templates/_helpers.tpl
charts/mapproxy/templates/configmap.yaml
charts/mapproxy/templates/deployment.yaml
charts/mapproxy/templates/ingress.yaml
charts/mapproxy/templates/pvc.yaml
charts/mapproxy/templates/service.yaml
charts/mapproxy/templates/serviceaccount.yaml
charts/mapproxy/templates/tests/test-connection.yaml
charts/mapproxy/values.yaml

This PR introduces an initial version of an Helm chart that uses [`terrestris/mapproxy`](https://github.com/terrestris/docker-mapproxy/) docker image for Kubernetes cluster deployments. Beside a running instance of `terrestris/mapproxy`, a nginx is deployed to handle mapproxy's UWSGI requests. The used version of `mapproxy` can be defined in `Chart.yaml`, in particular in property `appVersion`. By default the deployed mapproxy in cluster will provide a preconfigured cache of [OWS-terrestris](https://www.terrestris.de/de/openstreetmap-wms/). 
The following mapproxy specific parameters can be configured in (custom) `values.yaml`:
* `mapproxy.uwsgiProcesses`: The number of uwsgi processes (default: 2)
* `mapproxy.uwsgiThreads`: The number of uwsgi threads (default: 20)
* …

Introduce Helm chart for (terrestris) mapproxy

---

.github/workflows/release.yaml

See https://github.com/helm/chart-releaser-action
Helm charts will be released to https://github.com/terrestris/helm-charts/tree/gh-pages after successful merge to `main` branch an be available afterwards as helm repository:
```
helm repo add terrestris-helm https://terrestris.github.io/helm-charts`
```

Release helm charts to repo located on branch gh-pages

---

.editorconfig
charts/geoserver/Chart.yaml
charts/mapfish-print/Chart.yaml
charts/mapfish-print/README.md
charts/mapfish-print/templates/configmap.yaml
charts/mapfish-print/templates/deployment.yaml
charts/mapfish-print/values.yaml

See title. Also fixes the geoserver version, which was missing in the last MR (#12).

allow to download printconfig which requires credentials

---

charts/mapfish-print/Chart.yaml
charts/mapfish-print/README.md
charts/mapfish-print/templates/deployment.yaml
charts/mapproxy/Chart.yaml
charts/mapproxy/README.md
charts/mapproxy/templates/deployment.yaml

mapfish-print:
- adds `extraInitEnv` and `extraInitEnvFrom` which allows to configure environment variables only for the init container
mapproxy:
- introduces `extraEnv` and `extraEnvFrom`

allow more flexibility for extra env

---

charts/postgis/Chart.yaml
charts/postgis/README.md
charts/postgis/templates/configmap.yaml
charts/postgis/templates/statefulset.yaml
charts/postgis/values.yaml

Introduces new config `dataImport` which allows to download and extract a remove archive. This will overwrite the existing data directory.

feat: allow to initialize data directory from remote URL

---

charts/postgis/Chart.yaml
charts/postgis/templates/statefulset.yaml
charts/postgis/values.yaml

Allows to configure `livenessProbe`, `readinessProbe` and `startupProbe` options.

feat: add configuration options for probes

---

charts/mapproxy/Chart.yaml
charts/mapproxy/README.md
charts/mapproxy/templates/deployment.yaml
charts/mapproxy/values.yaml

Similar to the configuration of `mapproxy.yaml`, this PR introduces the configuration of the `seed.yaml` via a configmap (e.g. `your-seed-config-map`):
```yaml
...
customSeedConfig:
enabled: true
configMapName: your-seed-config-map
```

Make seed.yaml configurable via configmap

---

charts/geoserver/Chart.yaml
charts/mapfish-print/Chart.yaml
charts/postgis/Chart.yaml

Follow-up of https://github.com/terrestris/helm-charts/pull/23:
- releases version 1.0.0 for geoserver, mapfish-print and postgis
- also updates the postgis image to the `15-3.3-alpine`

version 1.0.0 releases

---

charts/postgis/Chart.yaml
charts/postgis/templates/pvc.yaml
charts/postgis/templates/statefulset.yaml
charts/postgis/values.yaml

By this PR, the defintion of the `PersistantVolumeClaim` for `postgis` is externalized and made more configurable (e.g. the `StorageClass`).

feat: make pvc and storage class more configurable

---

charts/mapproxy/Chart.yaml
charts/mapproxy/README.md
charts/mapproxy/templates/configmap.yaml
charts/mapproxy/templates/pvc.yaml
charts/mapproxy/templates/statefulset.yaml
charts/mapproxy/values.yaml

Since the official mapproxy repository provides an image containing a pre-configured nginx, the one in the actual helm chart can be omitted.
In addition, the resources have been fixed (e.g. paths to configs / mounts) in order to match the configs in the official [`mapproxy` docker image](https://github.com/mapproxy/mapproxy/pkgs/container/mapproxy%2Fmapproxy) and the persistent volume claim definition uses storage class only if set.

Use official mapproxy-nginx image in helm chart and fix resources

---

charts/geoserver/values.yaml
charts/mapfish-print/values.yaml
charts/mapproxy/values.yaml
charts/postgis/values.yaml

From experience in projects it is not a good idea to set cpu limits as this will heavily slow down your application in certain scenarios.
Read more here: https://home.robusta.dev/blog/stop-using-cpu-limits

Remove cpu limits

---

charts/gnos/Chart.yaml
charts/gnos/README.md
charts/gnos/templates/configmap.yaml
charts/gnos/templates/deployment.yaml
charts/gnos/templates/elasticsearch.yaml
charts/gnos/templates/kibana.yaml
charts/gnos/values.yaml

1. Install custom resource definitions for elasticsearch
```shell
kubectl create -f https://download.elastic.co/downloads/eck/2.9.0/crds.yaml
```
2. Install the elasticsearch operator with its RBAC rules:
```shell
kubectl apply -f https://download.elastic.co/downloads/eck/2.9.0/operator.yaml
```
see here https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.html#k8s-deploy-eck
This directory contains a helm chart using the official [Geonetwork OpenSource (GNOS)](https://github.com/geonetwork/docker-geonetwork) docker image for Kubernetes cluster deployments.
Since GNOS requires a running instance of ElasticSearch (and Kibana) this is included using custom resources and corresponding configuration files.
The GNOS version can be defined in the `Chart.yaml` file by setting …

Finalize GNOS helm chart

---

.github/workflows/lint.yaml
.github/workflows/release.yaml
README.md

…and configure pipeline such that changes in `**/*/README.md` are ignored.

chore: Bump versions

---

.github/workflows/lint.yaml

There are problems with the current gh action pipelines due to outdated versions (see [here](https://github.com/terrestris/helm-charts/pull/43)). This PR will fix it!

Use latest gh action versions

---

charts/postgis/Chart.yaml
charts/postgis/templates/statefulset.yaml

This adds the missing "args" to specify where postgres should load the config from.

Add missing "args"

---

charts/mapproxy/Chart.yaml
charts/mapproxy/templates/statefulset.yaml
charts/mapproxy/values.yaml

* use alpine based docker image in v2.0.2
* fix: probe configurations

Upgrade mapproxy image

---

charts/postgis/Chart.yaml
charts/postgis/templates/configmap.yaml

See title.
Required, to pass configured string entries to `postgresl.conf` correctly, e.g.
```
postgres:
conf: |
jit = off
```

fix: check for existing postgresql - config

---

charts/geoserver/Chart.yaml
charts/geoserver/README.md
charts/geoserver/templates/configmap.yaml
charts/geoserver/templates/statefulset.yaml
charts/geoserver/values.yaml
charts/shogun/Chart.yaml

This introduces an optional new feature to initialize geofence configuration.
It can be activated by setting `geofence.enableInitScript` to `true`. As the default value for this flag is `false`, for existing deployments that update to the new chart version, nothing should change.

feat: introduce optional geofence initialization

---

charts/geoserver/Chart.yaml
charts/geoserver/README.md
charts/geoserver/templates/configmap.yaml
charts/geoserver/templates/statefulset.yaml
charts/geoserver/values.yaml

Analogous to https://github.com/terrestris/helm-charts/pull/92 this PR adds the optional possibility to run a script to initialize the configuration of a the [GeoServer Monitoring Extension](https://docs.geoserver.org/stable/en/user/extensions/monitoring/configuration.html).
The configuration that should be used for the monitoring extension can be defined in the new properties of the `values.yaml`.
By default, this feature is disabled, so nothing changes for existing deployments in case of a chart update.

feat: introduce gs monitor extension init script

---

charts/geoserver/Chart.yaml
charts/geoserver/templates/configmap.yaml

For some reason `cp /path/{file1,file2}.txt /target/` does not work in the init container (seems that internally some symlink magic is used that might be a problem here)
This change fixes the problem

fix: fixes non-working cp command

---

charts/geoserver/Chart.yaml
charts/geoserver/templates/ingress.yaml
charts/geoserver/values.yaml

This updates the geoserver ingress definition to the latest "best practice" version.
The new `ingress.yaml` is based on the content of the `ingress.yaml` created by "helm create geoserver" (in a separate tmp dir).
The `values.yaml` has been adjusted to fit the new structure.

feat: update geoserver ingress

---

charts/geoserver/Chart.yaml
charts/geoserver/README.md
charts/geoserver/templates/configmap.yaml
charts/geoserver/templates/statefulset.yaml
charts/geoserver/values.yaml

We configure the `geofence-datasource-ovr.properties`, but we do not care yet about the existence of the underlying db...

feat: create geofence db in case it does not yet exist
