charts/mapproxy/templates/deployment.yaml
Should work even if demo is disabled.
See title. @ahennr Please review
=> use WMS url in health check

charts/mapproxy/Chart.yaml
=> Bump version of mapproxy image to v1.15.1

.github/workflows/lint.yaml, README.md, charts/mapproxy/Chart.yaml, charts/mapproxy/values.yaml, charts/postgis/Chart.yaml
Title says it all. Based on the example workflow shown [here](https://github.com/helm/chart-testing-action) the uses Helm `ct` tool (https://github.com/helm/chart-testing) and a kind cluster to lint and test charts.
=> Introduce workflow for helm chart linting and testing

charts/geoserver/README.md, charts/geoserver/templates/configmap.yaml, charts/geoserver/templates/statefulset.yaml, charts/geoserver/values.yaml, charts/mapfish-print/templates/configmap.yaml
- improves init-data.sh script: uses `storage.dataDir` parameter
- fix typo in mapfish-print helm chart
- improve docs
=> small improvements to the geoserver helm chart

charts/postgis/Chart.yaml, charts/postgis/README.md, charts/postgis/templates/configmap.yaml, charts/postgis/templates/statefulset.yaml, charts/postgis/values.yaml
Refactors the database initalization:
* provided SQL files are extracted and imported at startup
=> refactor: initialize db via psql

charts/postgis/Chart.yaml, charts/postgis/templates/statefulset.yaml, charts/postgis/values.yaml
See title. @terrestris/devs Please review
=> fix: allow to configure `POSTGRES_DB` environment

charts/geoserver/Chart.yaml, charts/geoserver/templates/statefulset.yaml, charts/geoserver/values.yaml
=> fix: fix additional libs installation

charts/geoserver/Chart.yaml
=> chore: update geoserver version

charts/mapproxy/Chart.yaml, charts/mapproxy/templates/deployment.yaml
=> fix: volume mount for custom seed.yaml from configmap

charts/mapproxy/Chart.yaml, charts/mapproxy/templates/deployment.yaml
=> fix: mount seed.yaml to seperated path

charts/postgis/Chart.yaml, charts/postgis/README.md, charts/postgis/templates/statefulset.yaml
=> fix: name of datadir and adds some documentation

charts/geoserver/Chart.yaml, charts/geoserver/values.yaml
Plz review @terrestris/devs @jorzekowsky
=> fix: homogenize memory limits JVM and Cluster resources

charts/mapproxy/Chart.yaml, charts/mapproxy/templates/statefulset.yaml, charts/mapproxy/values.yaml
See title, plz review @terrestris/devs
=> Update mapproxy to official 1.16.0 image

charts/geoserver/Chart.yaml, charts/geoserver/README.md, charts/geoserver/values.yaml
=> Use official geoserver image in GeoServer helm chart

.gitignore, charts/gnos/Chart.yaml, charts/gnos/templates/deployment.yaml
See title
Plz review @hwbllmnn
=> Fix helm lintint errors for GNOS helm chart

charts/geoserver/Chart.yaml
=> chore: bump geoserver version and bump app version correctly

charts/mapfish-print/Chart.yaml
Use latest available versions of GeoServer and Mapfish Print
=> Use latest versions

charts/geoserver/README.md
Title says it all :man_shrugging:
=> fix: repo reference in README

charts/postgis/Chart.yaml, charts/postgis/templates/statefulset.yaml, charts/postgis/values.yaml
=> fix(PostGIS): use extra environment variables correctly

.github/workflows/lint.yaml, charts/geoserver/Chart.yaml
=> chore: bump geoserver version to v2.24.1

charts/postgis/Chart.yaml, charts/postgis/README.md, charts/postgis/templates/configmap.yaml, charts/postgis/templates/statefulset.yaml, charts/postgis/values.yaml
This adds the possibility to add a postgresql.conf via configmap.yaml
=> Introduce postgresql.conf to configmap

charts/postgis/Chart.yaml, charts/postgis/README.md, charts/postgis/templates/NOTES.txt, charts/postgis/templates/configmap.yaml, charts/postgis/templates/secret-custom-user.yaml, charts/postgis/templates/secret-default-user.yaml, charts/postgis/templates/statefulset.yaml, charts/postgis/values.yaml
In addition, the PostGIS version was updated to v3.4 (including postgresql update to v16).
=> feat(PostGIS): use secrets as preferred method to get db passwords

charts/postgis/Chart.yaml, charts/postgis/templates/statefulset.yaml
=> fix(PostGIS): fix containerPort config

charts/geoserver/Chart.yaml, charts/geoserver/templates/configmap.yaml
See title.
Please review @terrestris/devs
=> fix: extract command for geoserver init data archive

charts/geoserver/Chart.yaml, charts/geoserver/templates/statefulset.yaml, charts/geoserver/values.yaml
Please review @terrestris/devs
=> feat: improve configuration of probes in GeoServer helm chart

charts/geoserver/Chart.yaml
=> chore: bump geoserver to v2.24.4

charts/geoserver/Chart.yaml, charts/geoserver/values.yaml
=> chore: bump geoserver to v2.25.2

charts/shogun-client/Chart.yaml
=> bump version of SHOGun GIS client

charts/shogun-admin/Chart.yaml
=> bump version of SHOGun Admin

charts/shogun-boot/Chart.yaml
=> Bump version of SHOGun boot

charts/shogun/Chart.yaml, charts/shogun/values.yaml
Bump all relevant, depending helm charts of SHOGun helm chart.
=> Bump depending chart versions of SHOGun

charts/shogun/Chart.yaml, charts/shogun/values.yaml
=> fix: load public print config by default

charts/shogun-boot/Chart.yaml, charts/shogun-boot/templates/statefulset.yaml, charts/shogun-boot/values.yaml
=> feat(SHOGun boot): make probes configurable

charts/shogun/Chart.yaml
=> Bump helm chart version of SHOGun boot

charts/shogun-boot/Chart.yaml, charts/shogun-boot/templates/configmap.yaml, charts/shogun-boot/values.yaml
=> feat(SHOGun Boot): make keycloak values configurable

charts/shogun/Chart.yaml
=> chore(SHOGun): update SHOGun boot helm chart

charts/mapfish-print/Chart.yaml, charts/mapfish-print/templates/ingress.yaml, charts/mapfish-print/values.yaml
same as https://github.com/terrestris/helm-charts/pull/97 for mapfish print
=> feat: update mapfish print ingress
